import type { TechLogoKey } from './techLogos'
/** Audited against main 5438bff. Update with package.json and README when the stack changes. */
export const techGroups = ['Interface', 'Data & Identity', 'QR & Reports', 'Browser Tools', 'Build & Delivery'] as const
export type TechGroup = typeof techGroups[number]
export const techStack: {name:string;group:TechGroup;mark:string;logos?:TechLogoKey[];purpose:string;description:string;about:string;flow:[string,string,string]}[] = [
 {name:'React 19',group:'Interface',mark:'UI',logos:["react"],purpose:'Components and state',about:"React builds interfaces from reusable components. State and hooks keep those components in sync as people interact with the app.",flow:["User action", "React state", "Updated view"],description:'Components, hooks, lazy loading, and state bring each workspace together.'},
 {name:'React DOM',group:'Interface',mark:'DOM',logos:["react"],purpose:'Rendering and dialogs',about:"React DOM connects React components to browser elements. Portals let a dialog appear outside the layout that opened it.",flow:["React component", "DOM rendering", "App screen"],description:'Renders the app and places dialogs above the surrounding interface with portals.'},
 {name:'TypeScript',group:'Interface',mark:'TS',logos:["typescript"],purpose:'Typed code',about:"TypeScript adds type checking to JavaScript. It helps catch mismatched component properties and unexpected data shapes during development.",flow:["Typed code", "Build checks", "JavaScript"],description:'Typed components and data models with strict checks before every production build.'},
 {name:'HTML & Custom CSS',group:'Interface',mark:'CSS',logos:["html5", "css"],purpose:'Layout and theme colors',about:"HTML defines page structure; CSS controls presentation. Shared variables let the app reuse its colors, spacing, and responsive layouts.",flow:["Page structure", "Theme styles", "Responsive UI"],description:'Responsive layouts, theme variables, gradients, and carefully scoped component styles.'},
 {name:'Lucide React',group:'Interface',mark:'ICON',logos:["lucide"],purpose:'Interface icons',about:"Lucide provides SVG icons as React components. A common icon system makes actions easier to recognize across different screens.",flow:["App action", "Lucide icon", "Visual cue"],description:'A shared set of lightweight interface icons, from camera controls to navigation.'},
 {name:'CSS & Web Animations',group:'Interface',mark:'FX',logos:["css"],purpose:'Transitions and motion',about:"CSS transitions and keyframes animate visual changes. The Web Animations API adds programmatic control for effects that respond to interaction.",flow:["Interaction", "Motion effect", "Visual feedback"],description:'Keyframes and the Web Animations API power optional transitions, illustrations, and click effects.'},
 {name:'Supabase JavaScript SDK',group:'Data & Identity',mark:'SDK',logos:["supabase"],purpose:'Database connection',about:"The Supabase client library provides JavaScript methods for working with the app\u2019s backend, including queries, sessions, and remote functions.",flow:["App request", "Supabase client", "Backend response"],description:'Connects the interface to authentication, database queries, and server-side functions.'},
 {name:'Supabase Auth & Google OAuth',group:'Data & Identity',mark:'AUTH',logos:["supabase", "google"],purpose:'Google sign-in and sessions',about:"OAuth allows Google to handle sign-in. Supabase Auth manages the resulting app session so the app can recognize the signed-in account.",flow:["Google sign-in", "Auth session", "App account"],description:'Google sign-in and session management connect people to their app accounts.'},
 {name:'PostgreSQL & SQL Functions',group:'Data & Identity',mark:'SQL',logos:["postgresql"],purpose:'Stored records and functions',about:"PostgreSQL stores related data in tables. SQL functions carry out database operations that the frontend can call through the backend.",flow:["App operation", "SQL function", "Stored records"],description:'Relational records and remote procedure calls support members, services, reporting, and reviews.'},
 {name:'Row Level Security',group:'Data & Identity',mark:'RLS',logos:["postgresql"],purpose:'Database access policies',about:"Row Level Security applies database policies to individual rows. Actual access depends on deployed policies and function permissions, not simply whether a button is visible.",flow:["Data request", "Access policies", "Allowed records"],description:'Database access depends on deployed policies and function permissions, beyond the visible UI.'},
 {name:'Supabase Realtime',group:'Data & Identity',mark:'LIVE',logos:["supabase"],purpose:'Live attendance updates',about:"Realtime subscriptions notify the app when relevant database changes occur. The interface can refresh attendance information without requiring a manual reload.",flow:["Database change", "Subscription", "Refreshed totals"],description:'Database change subscriptions refresh dashboard and service check-in totals.'},
 {name:'pgcrypto & UUIDs',group:'Data & Identity',mark:'ID',logos:["postgresql"],purpose:'Unique record identifiers',about:"UUIDs are identifiers designed to avoid collisions. The initial schema enables PostgreSQL\u2019s pgcrypto extension and generates identifiers for records and QR tokens.",flow:["New record", "Generated UUID", "Unique identifier"],description:'The initial database schema enables pgcrypto and uses generated UUIDs for identifiers and QR tokens.'},
 {name:'html5-qrcode',group:'QR & Reports',mark:'SCAN',logos:[],purpose:'Camera QR scanning',about:"html5-qrcode decodes QR patterns from camera frames. The app can then use the scanned value in its attendance check-in workflow.",flow:["Camera frame", "QR decoding", "Check-in workflow"],description:'Reads QR codes from the camera, with camera switching and supported torch controls.'},
 {name:'qrcode.react',group:'QR & Reports',mark:'QR',logos:[],purpose:'Member QR generation',about:"qrcode.react renders a value as a QR graphic. LifeCity uses member tokens to generate scannable codes without putting personal details directly in the image.",flow:["Member token", "QR rendering", "Member QR"],description:'Creates SVG member QR codes from opaque tokens rather than personal details.'},
 {name:'Papa Parse',group:'QR & Reports',mark:'CSV',logos:[],purpose:'CSV import parsing',about:"Papa Parse turns CSV text into structured rows and fields. LifeCity uses that output for member import mapping and validation; export formatting is handled separately.",flow:["CSV file", "Parsed rows", "Import review"],description:'Parses member CSV imports for field mapping and validation. Exports use app-owned CSV formatters.'},
 {name:'Canvas, SVG & File APIs',group:'QR & Reports',mark:'PNG',logos:["html5"],purpose:'ID images and downloads',about:"Canvas and SVG draw images; File APIs work with selected or generated files. Together they support member ID images, QR downloads, and report files.",flow:["Member or report", "Render / format", "Downloaded file"],description:'Render member IDs and QR downloads, read selected files, and save generated exports.'},
 {name:'Media & Fullscreen APIs',group:'Browser Tools',mark:'CAM',logos:["javascript"],purpose:'Camera and kiosk mode',about:"Browser media APIs request access to camera devices. The Fullscreen API lets the scanner use more screen space during kiosk check-in.",flow:["Camera permission", "Video stream", "Scanner view"],description:'Camera access and fullscreen kiosk presentation work within browser and device capabilities.'},
 {name:'Web Audio API',group:'Browser Tools',mark:'SFX',logos:["javascript"],purpose:'Scan confirmation sounds',about:"The Web Audio API creates and controls sound in the browser. Playback is subject to browser rules, such as requiring a user interaction first.",flow:["Scan result", "Audio signal", "Sound feedback"],description:'Generates scanner feedback sounds where browser interaction rules allow playback.'},
 {name:'Intl Date & Time',group:'Browser Tools',mark:'TIME',logos:["javascript"],purpose:'Local date formatting',about:"JavaScript date tools and Intl format timestamps for people to read. LifeCity uses them for service dates and reports, including Manila time.",flow:["Timestamp", "Time-zone format", "Readable date"],description:'Formats service and reporting dates, including Asia/Manila time.'},
 {name:'Local Storage & Web Crypto',group:'Browser Tools',mark:'WEB',logos:["javascript"],purpose:'Device preferences and IDs',about:"Local Storage retains small preferences on a device. Web Crypto also provides browser-generated identifiers used by the app\u2019s feedback retry handling.",flow:["Device settings", "Browser storage", "Saved preference"],description:'Stores the device’s motion preference and creates feedback request IDs for retry handling.'},
 {name:'Native Dialog & ResizeObserver',group:'Browser Tools',mark:'A11Y',logos:["html5"],purpose:'Modals and layout sizing',about:"Native dialogs provide browser-managed modal behavior. ResizeObserver reports element size changes so interactive layouts can respond to their available space.",flow:["Open panel", "Dialog / sizing", "Adjusted layout"],description:'Native modal behavior and size observation support interactive panels without a UI framework.'},
 {name:'Vite 7 & React Plugin',group:'Build & Delivery',mark:'DEV',logos:["vite"],purpose:'Dev server and production build',about:"Vite serves the app during development and bundles it for production. Its React plugin supports the React development workflow.",flow:["Source files", "Vite build", "Web assets"],description:'Runs the development server and bundles production assets with @vitejs/plugin-react.'},
 {name:'Node.js & npm',group:'Build & Delivery',mark:'NPM',logos:["nodedotjs", "npm"],purpose:'Runtime and dependencies',about:"Node.js runs JavaScript development tools outside the browser. npm installs packages and runs the project\u2019s scripts using its dependency configuration.",flow:["Project packages", "npm install", "Development tools"],description:'Run development tools and install the dependency versions recorded in package-lock.json.'},
 {name:'TypeScript Type Packages',group:'Build & Delivery',mark:'TYPES',logos:["typescript"],purpose:'Library type definitions',about:"Type definition packages describe the inputs and outputs of JavaScript libraries. TypeScript uses them for editor suggestions and compile-time checks.",flow:["Library types", "Type checking", "Editor guidance"],description:'React, React DOM, and Papa Parse type definitions support editor assistance and build checks.'},
 {name:'Web App Manifest',group:'Build & Delivery',mark:'APP',logos:["html5"],purpose:'Home-screen app metadata',about:"A web manifest supplies an app name, icons, and display preferences for supported browsers. It does not by itself provide offline functionality.",flow:["App metadata", "Browser support", "Home-screen identity"],description:'Provides app icons, standalone display metadata, and a home-screen identity. Offline caching is not implemented.'},
 {name:'Git & GitHub',group:'Build & Delivery',mark:'GIT',logos:["git", "github"],purpose:'Version control and repository',about:"Git tracks revisions to project files. GitHub hosts the repository so the code and its history can be reviewed and shared.",flow:["Code changes", "Git history", "GitHub repository"],description:'Track source changes and host the public LifeCity Attendance repository.'},
 {name:'Vercel',group:'Build & Delivery',mark:'HOST',logos:["vercel"],purpose:'Web hosting',about:"Vercel serves the deployed web application. Build and hosting configuration connect the project source to the public site.",flow:["Project source", "Deployment build", "Hosted app"],description:'Hosts the web deployment. Hosting settings live outside this repository.'}
]
